/**
 * Articles database
 *
 * Add new articles to article-queue.txt and run:
 * node batch-processor.js
 */

const ARTICLES = [
  {
    date: "2026-01-01",
    answer: "Josh Allen",
    sections: [
      "Early life",
      "College career",
      "College career → Reedley College",
      "College career → Wyoming",
      "College career → College statistics",
      "Professional career",
      "Professional career → Pre-draft",
      "Professional career → 2018 season",
      "Professional career → 2019 season",
      "Professional career → 2020 season",
      "Professional career → 2021 season",
      "Professional career → 2022 season",
      "Professional career → 2023 season",
      "Professional career → 2024 season",
      "Professional career → 2025 season",
      "NFL career statistics",
      "NFL career statistics → Regular season",
      "NFL career statistics → Postseason",
      "Records and achievements",
      "Records and achievements → NFL records",
      "Records and achievements → Bills franchise records",
      "Records and achievements → Accolades",
      "Player profile",
      "Personal life",
      "Personal life → Golf",
      "Personal life → Business ventures",
      "Personal life → Philanthropy"
    ]
  },
  {
    date: "2026-01-02",
    answer: "Ryan Seacrest",
    sections: [
      "Early life",
      "Career",
      "Career → Television hosting",
      "Career → Radio hosting",
      "Career → Television producing",
      "Career → Business ventures",
      "Career → Fashion",
      "Philanthropy",
      "Personal life",
      "Credits",
      "Credits → Radio",
      "Credits → Film",
      "Credits → Television"
    ]
  },
  {
    date: "2026-01-04",
    answer: "Nicolás Maduro",
    sections: [
      "Early and personal life",
      "Early career",
      "Early career → Education and union work",
      "Early career → National Assembly",
      "Foreign minister of Venezuela",
      "Foreign minister of Venezuela → 2006 detention in New York",
      "Vice President of Venezuela",
      "Vice President of Venezuela → Interim president",
      "Presidency",
      "Presidency → International relations",
      "Presidency → Assassination attempts",
      "Controversies",
      "Controversies → Disputed presidency",
      "Controversies → Dictatorship accusations",
      "Controversies → Birthplace and nationality",
      "Controversies → Conspiracy theories",
      "Controversies → Censorship",
      "Controversies → Human rights",
      "Controversies → Judicial independence",
      "Controversies → Alleged drug trafficking and money laundering incidents",
      "Controversies → Homophobic statements",
      "Controversies → Hunger crisis",
      "Controversies → Corruption",
      "Controversies → Sanctions",
      "Capture",
      "Public opinion",
      "In popular culture",
      "Awards and honours",
      "Awards and honours → Others",
      "Elections",
      "Elections → 2013 presidential campaign",
      "Elections → 2018 presidential campaign",
      "Elections → 2024 presidential campaign",
      "Elections → Electoral history"
    ]
  },
  {
    date: "2026-01-03",
    answer: "Mao Zedong",
    sections: [
      "English romanisation of name",
      "Early life",
      "Early revolutionary activity",
      "Civil War",
      "Civil War → Nanchang and Autumn Harvest Uprisings: 1927",
      "World War II",
      "Leadership of China",
      "Leadership of China → Korean War",
      "Leadership of China → Social reform",
      "Leadership of China → Three-anti and Five-anti Campaigns",
      "Leadership of China → Five-year plans",
      "Leadership of China → Military projects",
      "Leadership of China → Great Leap Forward",
      "Leadership of China → Split from Soviet Union",
      "Leadership of China → Third Front",
      "Leadership of China → Cultural Revolution",
      "State visits",
      "Death and aftermath",
      "Legacy",
      "Legacy → Assessment in China",
      "Legacy → Assessment in Western world",
      "Legacy → Third World",
      "Legacy → Military strategy",
      "Legacy → Literature",
      "Legacy → Public image",
      "Personal life and family",
      "Personal life and family → Family",
      "Writings and calligraphy",
      "Writings and calligraphy → Literary works",
      "Portrayal in media",
      "Portrayal in media → General",
      "Portrayal in media → Commentary"
    ]
  },
  {
    date: "2026-01-04",
    answer: "Usain Bolt",
    sections: [
      "Early years",
      "Early years → Early competitions",
      "Early years → Rise to prominence",
      "Professional athletics career",
      "Professional athletics career → World-record breaker",
      "Professional athletics career → 2008 Summer Olympics",
      "Professional athletics career → After the 2008 Olympics",
      "Professional athletics career → 2009 Berlin World Championships",
      "Professional athletics career → 2010 Diamond League and broken streak",
      "Professional athletics career → 2011 World Championships",
      "Professional athletics career → 2012 Summer Olympics",
      "Professional athletics career → 2013 World Championships",
      "Professional athletics career → 2014: Injury and Commonwealth Games",
      "Professional athletics career → 2015 Beijing World Championships",
      "Professional athletics career → 2016 Rio Olympics",
      "Professional athletics career → 2017 season",
      "Personal life",
      "Personal life → Financial crisis",
      "Personal life → Family",
      "Personal life → Other sports",
      "Personal life → Documentary film",
      "Sponsorships and advertising work",
      "Entrepreneurship",
      "Music production",
      "Recognition",
      "Statistics",
      "Statistics → Personal bests",
      "Statistics → Records",
      "Statistics → World rankings",
      "Statistics → International competitions",
      "Statistics → National titles",
      "Statistics → Circuit wins",
      "Publications",
      "Publications → Videos"
    ]
  },
  {
    date: "2026-01-05",
    answer: "Robert Downey Jr.",
    sections: [
      "Early life and acting background",
      "Career",
      "Other ventures",
      "Other ventures → Music",
      "Other ventures → Social activism",
      "Personal life",
      "Artistry and public image",
      "Acting credits and accolades",
      "Discography",
      "Discography → Studio album",
      "Discography → Soundtrack appearances",
      "Printed sources"
    ]
  },
  {
    date: "2026-01-06",
    answer: "Tupac Shakur",
    sections: [
      "Early life",
      "Early life → Birth and ancestry",
      "Music career",
      "Music career → 1995:",
      "Music career → Posthumous albums",
      "Poetry collection",
      "Personal life",
      "Legal issues",
      "Legal issues → 1993 shooting in Atlanta",
      "Legal issues → 1994 Quad Studios shooting",
      "Legal issues → Setup accusations involving the Notorious B.I.G.",
      "Legal issues → Other criminal or civil cases",
      "Murder and aftermath",
      "Artistry",
      "Artistry → Musical style",
      "Artistry → Vocal style",
      "Legacy and remembrance",
      "Legacy and remembrance → Final resting place in Soweto",
      "Legacy and remembrance → Tupac Amaru Shakur Foundation",
      "Legacy and remembrance → Academic appraisal",
      "Legacy and remembrance → Multimedia releases",
      "Legacy and remembrance → Film and stage",
      "Legacy and remembrance → Awards and honors",
      "Discography",
      "Filmography",
      "Filmography → Portrayals in film",
      "Filmography → Documentaries"
    ]
  },
  {
    date: "2026-01-07",
    answer: "Hillary Clinton",
    sections: [
      "Early life and education",
      "Early life and education → Early life",
      "Early life and education → Wellesley College years",
      "Early life and education → Yale Law School and postgraduate studies",
      "Early life and education → From the East Coast to Arkansas",
      "Early life and education → Early Arkansas years",
      "Early life and education → Later Arkansas years",
      "Early life and education → Bill Clinton 1992 presidential campaign",
      "Early life and education → Health care and other policy initiatives",
      "Early life and education → Scandals and investigations",
      "Early life and education → Response to Lewinsky scandal",
      "Early life and education → Traditional duties",
      "Early life and education → 2000 U.S. Senate election",
      "Early life and education → First term",
      "Early life and education → 2006 reelection campaign",
      "Early life and education → Second term",
      "2008 presidential campaign",
      "2008 presidential campaign → Nomination and confirmation",
      "2008 presidential campaign → Tenure",
      "2008 presidential campaign → Benghazi attack and subsequent hearings",
      "Email controversy",
      "2016 presidential campaign",
      "Post-2016 election activity",
      "Political positions",
      "Political positions → Economics",
      "Political positions → Domestic policy",
      "Political positions → LGBT rights",
      "Political positions → Immigration",
      "Political positions → Foreign policy",
      "Religious views",
      "Cultural and political image",
      "Awards and honors",
      "Books",
      "Ancestry",
      "Ancestry → Citations",
      "Ancestry → Works cited",
      "Ancestry → Official",
      "Ancestry → Media coverage",
      "Ancestry → Other"
    ]
  },
  {
    date: "2026-01-08",
    answer: "Glen Powell",
    sections: [
      "Early life and education",
      "Career",
      "Personal life",
      "Filmography",
      "Filmography → Film",
      "Filmography → Television",
      "Filmography → Audio",
      "Awards and nominations"
    ]
  },
  {
    date: "2026-01-09",
    answer: "Nelson Mandela",
    sections: [
      "Early life",
      "Early revolutionary activity",
      "Imprisonment",
      "End of apartheid and elections",
      "End of apartheid and elections → General election: 1994",
      "End of apartheid and elections → National reconciliation",
      "End of apartheid and elections → Domestic programmes",
      "End of apartheid and elections → Foreign affairs",
      "End of apartheid and elections → Withdrawing from politics",
      "Post-presidency and final years",
      "Political ideology",
      "Political ideology → Democracy",
      "Political ideology → Socialism and Marxism",
      "Personality and personal life",
      "Reception and legacy",
      "Reception and legacy → Biographies and popular media",
      "Reception and legacy → Footnotes"
    ]
  },
  {
    date: "2026-01-10",
    answer: "Robert F. Kennedy Jr.",
    sections: [
      "Early life and education",
      "Legal career",
      "Legal career → Conviction for heroin possession",
      "Legal career → Riverkeeper",
      "Legal career → Pace Environmental Litigation Clinic",
      "Legal career → Waterkeeper Alliance",
      "Legal career → New York City Watershed Agreement",
      "Legal career → Cape Wind",
      "Legal career → Other ventures",
      "Legal career → Minority and poor communities",
      "Legal career → International and indigenous rights",
      "Legal career → Military and Vieques",
      "Political aspirations",
      "Political aspirations → Candidacy aspirations",
      "Political aspirations → 2000s consideration for top environmental jobs",
      "Political aspirations → 2024 presidential campaign",
      "Political aspirations → Nomination and confirmation",
      "Political aspirations → Tenure",
      "Anti-vaccine advocacy and conspiracy theories on public health",
      "Anti-vaccine advocacy and conspiracy theories on public health → Vaccines and autism claims",
      "Anti-vaccine advocacy and conspiracy theories on public health → COVID-19",
      "Anti-vaccine advocacy and conspiracy theories on public health → Medical racism conspiracy theory",
      "Anti-vaccine advocacy and conspiracy theories on public health → Chemtrail conspiracy theory",
      "Anti-vaccine advocacy and conspiracy theories on public health → Miasma theory",
      "Anti-vaccine advocacy and conspiracy theories on public health → Pushback from the Kennedy family",
      "Political views",
      "Political views → Economic inequality",
      "Political views → Foreign affairs and military intervention",
      "Political views → Environmental policy",
      "Political views → Drug use",
      "Political views → Questioning the validity of elections",
      "Political views → Political endorsements",
      "Other views",
      "Other views → Food allergies",
      "Other views → Murder of Martha Moxley",
      "Other views → Assassinations of John F. Kennedy and Robert F. Kennedy",
      "Other views → Gender dysphoria",
      "Other views → Nicotine",
      "Other views → Raw milk",
      "Other views → Tanning beds",
      "Other views → Testosterone",
      "Personal life",
      "Personal life → General interests",
      "Personal life → Marriages and children",
      "Personal life → Health",
      "Personal life → Religion",
      "Personal life → Sexual assault allegations",
      "Personal life → Treatment of dead animals",
      "Selected works",
      "Note"
    ]
  },
  {
    date: "2026-01-11",
    answer: "Josh Allen",
    sections: [
      "Early life",
      "College career",
      "College career → Reedley College",
      "College career → Wyoming",
      "College career → College statistics",
      "Professional career",
      "Professional career → Pre-draft",
      "Professional career → 2018 season",
      "Professional career → 2019 season",
      "Professional career → 2020 season",
      "Professional career → 2021 season",
      "Professional career → 2022 season",
      "Professional career → 2023 season",
      "Professional career → 2024 season",
      "Professional career → 2025 season",
      "NFL career statistics",
      "NFL career statistics → Regular season",
      "NFL career statistics → Postseason",
      "Records and achievements",
      "Records and achievements → NFL records",
      "Records and achievements → Bills franchise records",
      "Records and achievements → Accolades",
      "Player profile",
      "Personal life",
      "Personal life → Golf",
      "Personal life → Business ventures",
      "Personal life → Philanthropy"
    ]
  },
  {
    date: "2026-01-12",
    answer: "Ryan Seacrest",
    sections: [
      "Early life",
      "Career",
      "Career → Television hosting",
      "Career → Radio hosting",
      "Career → Television producing",
      "Career → Business ventures",
      "Career → Fashion",
      "Philanthropy",
      "Personal life",
      "Credits",
      "Credits → Radio",
      "Credits → Film",
      "Credits → Television"
    ]
  },
  {
    date: "2026-01-13",
    answer: "Nicolás Maduro",
    sections: [
      "Early and personal life",
      "Early career",
      "Early career → Education and union work",
      "Early career → National Assembly",
      "Foreign minister of Venezuela",
      "Foreign minister of Venezuela → 2006 detention in New York",
      "Vice President of Venezuela",
      "Vice President of Venezuela → Interim president",
      "Presidency",
      "Presidency → International relations",
      "Presidency → Assassination attempts",
      "Controversies",
      "Controversies → Disputed presidency",
      "Controversies → Dictatorship accusations",
      "Controversies → Birthplace and nationality",
      "Controversies → Conspiracy theories",
      "Controversies → Censorship",
      "Controversies → Human rights",
      "Controversies → Judicial independence",
      "Controversies → Alleged drug trafficking and money laundering incidents",
      "Controversies → Homophobic statements",
      "Controversies → Hunger crisis",
      "Controversies → Corruption",
      "Controversies → Sanctions",
      "Capture",
      "Public opinion",
      "In popular culture",
      "Awards and honours",
      "Awards and honours → Others",
      "Elections",
      "Elections → 2013 presidential campaign",
      "Elections → 2018 presidential campaign",
      "Elections → 2024 presidential campaign",
      "Elections → Electoral history"
    ]
  },
  {
    date: "2026-01-14",
    answer: "Mao Zedong",
    sections: [
      "English romanisation of name",
      "Early life",
      "Early revolutionary activity",
      "Civil War",
      "Civil War → Nanchang and Autumn Harvest Uprisings: 1927",
      "World War II",
      "Leadership of China",
      "Leadership of China → Korean War",
      "Leadership of China → Social reform",
      "Leadership of China → Three-anti and Five-anti Campaigns",
      "Leadership of China → Five-year plans",
      "Leadership of China → Military projects",
      "Leadership of China → Great Leap Forward",
      "Leadership of China → Split from Soviet Union",
      "Leadership of China → Third Front",
      "Leadership of China → Cultural Revolution",
      "State visits",
      "Death and aftermath",
      "Legacy",
      "Legacy → Assessment in China",
      "Legacy → Assessment in Western world",
      "Legacy → Third World",
      "Legacy → Military strategy",
      "Legacy → Literature",
      "Legacy → Public image",
      "Personal life and family",
      "Personal life and family → Family",
      "Writings and calligraphy",
      "Writings and calligraphy → Literary works",
      "Portrayal in media",
      "Portrayal in media → General",
      "Portrayal in media → Commentary"
    ]
  }
];

// You can optionally encode the articles array to prevent casual spoilers
// Uncomment below to use encoded version:
/*
const ARTICLES_ENCODED = btoa(JSON.stringify(ARTICLES));
const ARTICLES = JSON.parse(atob(ARTICLES_ENCODED));
*/
